# Generated by Django 3.2.5 on 2021-07-15 09:39

import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, validators=[core.validators.course_code_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveBigIntegerField(validators=[core.validators.year_2xxx_validator])),
                ('end_year', models.PositiveBigIntegerField(validators=[core.validators.year_2xxx_validator])),
                ('type', models.CharField(choices=[('ALPHA', 'Alpha'), ('OMEGA', 'Omega')], max_length=5)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXAM', 'Exam'), ('CA', 'Ca')], max_length=4)),
                ('file', models.FileField(upload_to='uploads/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
        ),
    ]
