# Generated by Django 3.2.5 on 2021-07-17 15:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210715_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastquestion',
            name='file',
            field=models.FileField(upload_to=core.models.PastQuestion.course_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='pastquestion',
            unique_together={('semester', 'course', 'type')},
        ),
    ]
